"""兼容层：保留旧导入路径 src.prompts.case。"""

from . import CASE_GENERATION_SYSTEM_PROMPT, CASE_GENERATION_USER_PROMPT_TEMPLATE

__all__ = ["CASE_GENERATION_SYSTEM_PROMPT", "CASE_GENERATION_USER_PROMPT_TEMPLATE"]